# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Record": "00_core.ipynb",
         "Role": "00_core.ipynb",
         "Status": "00_core.ipynb",
         "readlen": "00_core.ipynb",
         "ByteStream": "00_core.ipynb",
         "FcgiHandler": "00_core.ipynb",
         "FcgiHandler.write": "00_core.ipynb",
         "FcgiHandler.print": "00_core.ipynb",
         "FcgiHandler.err": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/fastcgi/"

git_url = "https://github.com/fastai/fastcgi/tree/master/"

def custom_doc_links(name): return None
