# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Record": "00_core.ipynb",
         "Role": "00_core.ipynb",
         "Status": "00_core.ipynb",
         "readlen": "00_core.ipynb",
         "recv_record": "00_core.ipynb",
         "params": "00_core.ipynb",
         "send_record": "00_core.ipynb",
         "send_stream": "00_core.ipynb",
         "FcgiHandler": "00_core.ipynb",
         "TextWrapper": "00_core.ipynb",
         "FcgiHandler.print": "00_core.ipynb",
         "FcgiHandler.err": "00_core.ipynb",
         "FcgiHandler.content": "00_core.ipynb",
         "FcgiHandler.write": "00_core.ipynb",
         "ForkingUnixServer": "01_decorator.ipynb",
         "fastcgi": "01_decorator.ipynb",
         "ReuseThreadingServer": "02_http.ipynb",
         "HandlerException": "02_http.ipynb",
         "MinimalHTTPHandler": "02_http.ipynb"}

modules = ["core.py",
           "decorator.py",
           "http.py"]

doc_url = "https://fastai.github.io/fastcgi/"

git_url = "https://github.com/fastai/fastcgi/tree/master/"

def custom_doc_links(name): return None
